spring: 
    profiles: 
        active:
        -dev
---
server: 
    port: 8201
    application:
        name:microservicecloud-config-client
eureka:
    client:
        server-url:
            defaultZone:http://eureka-dev.com:7001/eureka/